### ISSUE TITLE
爬虫没问题 转种子程序运行起了 

### ISSUE THREAD

**Issue by rehe0x** [Cyrus97/magnet-crawler#1]
只是used-magnet加进去了  没看到下载文件

**Comment by Cyrus97** [comment]
种子是用 aria2 下载的，具体路径还是要看你的配置文件里的。

**Comment by Cyrus97** [comment]
首先检查一下项目下的 torrents 目录和 aria2 配置的下载目录，如果都没有文件，可能是 aria2 下载失败了😂。（这边代码可能有点问题，并不能完全同步 aria2 的下载情况反馈）
